# Generated by Django 5.2.1 on 2025-06-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='id',
        ),
        migrations.AddField(
            model_name='like',
            name='board_id',
            field=models.CharField(default=1, max_length=64, primary_key=True, serialize=False),
        ),
    ]
